// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package com.iflytek.cdstd.hungrycell.tcpserver.buff;

public final class GameServer {
  private GameServer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ServerDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.iflytek.cdstd.hungrycell.tcpserver.buff.ServerData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 service = 1;</code>
     */
    boolean hasService();
    /**
     * <code>required int32 service = 1;</code>
     */
    int getService();

    /**
     * <code>repeated int32 uids = 2;</code>
     */
    java.util.List<java.lang.Integer> getUidsList();
    /**
     * <code>repeated int32 uids = 2;</code>
     */
    int getUidsCount();
    /**
     * <code>repeated int32 uids = 2;</code>
     */
    int getUids(int index);

    /**
     * <code>optional .com.iflytek.cdstd.hungrycell.tcpserver.buff.MessageInfo messageInfo = 3;</code>
     */
    boolean hasMessageInfo();
    /**
     * <code>optional .com.iflytek.cdstd.hungrycell.tcpserver.buff.MessageInfo messageInfo = 3;</code>
     */
    com.iflytek.cdstd.hungrycell.tcpserver.buff.GameBuff.MessageInfo getMessageInfo();
    /**
     * <code>optional .com.iflytek.cdstd.hungrycell.tcpserver.buff.MessageInfo messageInfo = 3;</code>
     */
    com.iflytek.cdstd.hungrycell.tcpserver.buff.GameBuff.MessageInfoOrBuilder getMessageInfoOrBuilder();

    /**
     * <code>optional .com.iflytek.cdstd.hungrycell.tcpserver.buff.UserInfo userInfo = 4;</code>
     *
     * <pre>
     *add by wq 2017-05-26
     * </pre>
     */
    boolean hasUserInfo();
    /**
     * <code>optional .com.iflytek.cdstd.hungrycell.tcpserver.buff.UserInfo userInfo = 4;</code>
     *
     * <pre>
     *add by wq 2017-05-26
     * </pre>
     */
    com.iflytek.cdstd.hungrycell.tcpserver.buff.GameBuff.UserInfo getUserInfo();
    /**
     * <code>optional .com.iflytek.cdstd.hungrycell.tcpserver.buff.UserInfo userInfo = 4;</code>
     *
     * <pre>
     *add by wq 2017-05-26
     * </pre>
     */
    com.iflytek.cdstd.hungrycell.tcpserver.buff.GameBuff.UserInfoOrBuilder getUserInfoOrBuilder();

    /**
     * <code>optional .com.iflytek.cdstd.hungrycell.tcpserver.buff.GoldChange goldChange = 5;</code>
     *
     * <pre>
     *gs-&gt;tcpserver，由tcpserver执行数据库操作
     * </pre>
     */
    boolean hasGoldChange();
    /**
     * <code>optional .com.iflytek.cdstd.hungrycell.tcpserver.buff.GoldChange goldChange = 5;</code>
     *
     * <pre>
     *gs-&gt;tcpserver，由tcpserver执行数据库操作
     * </pre>
     */
    com.iflytek.cdstd.hungrycell.tcpserver.buff.GameServer.GoldChange getGoldChange();
    /**
     * <code>optional .com.iflytek.cdstd.hungrycell.tcpserver.buff.GoldChange goldChange = 5;</code>
     *
     * <pre>
     *gs-&gt;tcpserver，由tcpserver执行数据库操作
     * </pre>
     */
    com.iflytek.cdstd.hungrycell.tcpserver.buff.GameServer.GoldChangeOrBuilder getGoldChangeOrBuilder();
  }
  /**
   * Protobuf type {@code com.iflytek.cdstd.hungrycell.tcpserver.buff.ServerData}
   */
  public static final class ServerData extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.iflytek.cdstd.hungrycell.tcpserver.buff.ServerData)
      ServerDataOrBuilder {
    // Use ServerData.newBuilder() to construct.
    private ServerData(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ServerData(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ServerData defaultInstance;
    public static ServerData getDefaultInstance() {
      return defaultInstance;
    }

    public ServerData getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ServerData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              service_ = input.readInt32();
              break;
            }
            case 16: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                uids_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000002;
              }
              uids_.add(input.readInt32());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002) && input.getBytesUntilLimit() > 0) {
                uids_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000002;
              }
              while (input.getBytesUntilLimit() > 0) {
                uids_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 26: {
              com.iflytek.cdstd.hungrycell.tcpserver.buff.GameBuff.MessageInfo.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = messageInfo_.toBuilder();
              }
              messageInfo_ = input.readMessage(com.iflytek.cdstd.hungrycell.tcpserver.buff.GameBuff.MessageInfo.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(messageInfo_);
                messageInfo_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 34: {
              com.iflytek.cdstd.hungrycell.tcpserver.buff.GameBuff.UserInfo.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = userInfo_.toBuilder();
              }
              userInfo_ = input.readMessage(com.iflytek.cdstd.hungrycell.tcpserver.buff.GameBuff.UserInfo.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(userInfo_);
                userInfo_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
            case 42: {
              com.iflytek.cdstd.hungrycell.tcpserver.buff.GameServer.GoldChange.Builder subBuilder = null;
              if (((bitField0_ & 0x00000008) == 0x00000008)) {
                subBuilder = goldChange_.toBuilder();
              }
              goldChange_ = input.readMessage(com.iflytek.cdstd.hungrycell.tcpserver.buff.GameServer.GoldChange.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(goldChange_);
                goldChange_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000008;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          uids_ = java.util.Collections.unmodifiableList(uids_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.iflytek.cdstd.hungrycell.tcpserver.buff.GameServer.internal_static_com_iflytek_cdstd_hungrycell_tcpserver_buff_ServerData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.iflytek.cdstd.hungrycell.tcpserver.buff.GameServer.internal_static_com_iflytek_cdstd_hungrycell_tcpserver_buff_ServerData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.iflytek.cdstd.hungrycell.tcpserver.buff.GameServer.ServerData.class, com.iflytek.cdstd.hungrycell.tcpserver.buff.GameServer.ServerData.Builder.class);
    }

    public static com.google.protobuf.Parser<ServerData> PARSER =
        new com.google.protobuf.AbstractParser<ServerData>() {
      public ServerData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ServerData(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ServerData> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int SERVICE_FIELD_NUMBER = 1;
    private int service_;
    /**
     * <code>required int32 service = 1;</code>
     */
    public boolean hasService() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 service = 1;</code>
     */
    public int getService() {
      return service_;
    }

    public static final int UIDS_FIELD_NUMBER = 2;
    private java.util.List<java.lang.Integer> uids_;
    /**
     * <code>repeated int32 uids = 2;</code>
     */
    public java.util.List<java.lang.Integer>
        getUidsList() {
      return uids_;
    }
    /**
     * <code>repeated int32 uids = 2;</code>
     */
    public int getUidsCount() {
      return uids_.size();
    }
    /**
     * <code>repeated int32 uids = 2;</code>
     */
    public int getUids(int index) {
      return uids_.get(index);
    }

    public static final int MESSAGEINFO_FIELD_NUMBER = 3;
    private com.iflytek.cdstd.hungrycell.tcpserver.buff.GameBuff.MessageInfo messageInfo_;
    /**
     * <code>optional .com.iflytek.cdstd.hungrycell.tcpserver.buff.MessageInfo messageInfo = 3;</code>
     */
    public boolean hasMessageInfo() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .com.iflytek.cdstd.hungrycell.tcpserver.buff.MessageInfo messageInfo = 3;</code>
     */
    public com.iflytek.cdstd.hungrycell.tcpserver.buff.GameBuff.MessageInfo getMessageInfo() {
      return messageInfo_;
    }
    /**
     * <code>optional .com.iflytek.cdstd.hungrycell.tcpserver.buff.MessageInfo messageInfo = 3;</code>
     */
    public com.iflytek.cdstd.hungrycell.tcpserver.buff.GameBuff.MessageInfoOrBuilder getMessageInfoOrBuilder() {
      return messageInfo_;
    }

    public static final int USERINFO_FIELD_NUMBER = 4;
    private com.iflytek.cdstd.hungrycell.tcpserver.buff.GameBuff.UserInfo userInfo_;
    /**
     * <code>optional .com.iflytek.cdstd.hungrycell.tcpserver.buff.UserInfo userInfo = 4;</code>
     *
     * <pre>
     *add by wq 2017-05-26
     * </pre>
     */
    public boolean hasUserInfo() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .com.iflytek.cdstd.hungrycell.tcpserver.buff.UserInfo userInfo = 4;</code>
     *
     * <pre>
     *add by wq 2017-05-26
     * </pre>
     */
    public com.iflytek.cdstd.hungrycell.tcpserver.buff.GameBuff.UserInfo getUserInfo() {
      return userInfo_;
    }
    /**
     * <code>optional .com.iflytek.cdstd.hungrycell.tcpserver.buff.UserInfo userInfo = 4;</code>
     *
     * <pre>
     *add by wq 2017-05-26
     * </pre>
     */
    public com.iflytek.cdstd.hungrycell.tcpserver.buff.GameBuff.UserInfoOrBuilder getUserInfoOrBuilder() {
      return userInfo_;
    }

    public static final int GOLDCHANGE_FIELD_NUMBER = 5;
    private com.iflytek.cdstd.hungrycell.tcpserver.buff.GameServer.GoldChange goldChange_;
    /**
     * <code>optional .com.iflytek.cdstd.hungrycell.tcpserver.buff.GoldChange goldChange = 5;</code>
     *
     * <pre>
     *gs-&gt;tcpserver，由tcpserver执行数据库操作
     * </pre>
     */
    public boolean hasGoldChange() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional .com.iflytek.cdstd.hungrycell.tcpserver.buff.GoldChange goldChange = 5;</code>
     *
     * <pre>
     *gs-&gt;tcpserver，由tcpserver执行数据库操作
     * </pre>
     */
    public com.iflytek.cdstd.hungrycell.tcpserver.buff.GameServer.GoldChange getGoldChange() {
      return goldChange_;
    }
    /**
     * <code>optional .com.iflytek.cdstd.hungrycell.tcpserver.buff.GoldChange goldChange = 5;</code>
     *
     * <pre>
     *gs-&gt;tcpserver，由tcpserver执行数据库操作
     * </pre>
     */
    public com.iflytek.cdstd.hungrycell.tcpserver.buff.GameServer.GoldChangeOrBuilder getGoldChangeOrBuilder() {
      return goldChange_;
    }

    private void initFields() {
      service_ = 0;
      uids_ = java.util.Collections.emptyList();
      messageInfo_ = com.iflytek.cdstd.hungrycell.tcpserver.buff.GameBuff.MessageInfo.getDefaultInstance();
      userInfo_ = com.iflytek.cdstd.hungrycell.tcpserver.buff.GameBuff.UserInfo.getDefaultInstance();
      goldChange_ = com.iflytek.cdstd.hungrycell.tcpserver.buff.GameServer.GoldChange.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasService()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasMessageInfo()) {
        if (!getMessageInfo().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasUserInfo()) {
        if (!getUserInfo().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasGoldChange()) {
        if (!getGoldChange().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, service_);
      }
      for (int i = 0; i < uids_.size(); i++) {
        output.writeInt32(2, uids_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(3, messageInfo_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(4, userInfo_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeMessage(5, goldChange_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, service_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < uids_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(uids_.get(i));
        }
        size += dataSize;
        size += 1 * getUidsList().size();
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, messageInfo_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, userInfo_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, goldChange_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.iflytek.cdstd.hungrycell.tcpserver.buff.GameServer.ServerData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.iflytek.cdstd.hungrycell.tcpserver.buff.GameServer.ServerData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.iflytek.cdstd.hungrycell.tcpserver.buff.GameServer.ServerData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.iflytek.cdstd.hungrycell.tcpserver.buff.GameServer.ServerData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.iflytek.cdstd.hungrycell.tcpserver.buff.GameServer.ServerData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.iflytek.cdstd.hungrycell.tcpserver.buff.GameServer.ServerData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.iflytek.cdstd.hungrycell.tcpserver.buff.GameServer.ServerData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.iflytek.cdstd.hungrycell.tcpserver.buff.GameServer.ServerData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.iflytek.cdstd.hungrycell.tcpserver.buff.GameServer.ServerData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.iflytek.cdstd.hungrycell.tcpserver.buff.GameServer.ServerData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.iflytek.cdstd.hungrycell.tcpserver.buff.GameServer.ServerData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.iflytek.cdstd.hungrycell.tcpserver.buff.ServerData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.iflytek.cdstd.hungrycell.tcpserver.buff.ServerData)
        com.iflytek.cdstd.hungrycell.tcpserver.buff.GameServer.ServerDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.iflytek.cdstd.hungrycell.tcpserver.buff.GameServer.internal_static_com_iflytek_cdstd_hungrycell_tcpserver_buff_ServerData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.iflytek.cdstd.hungrycell.tcpserver.buff.GameServer.internal_static_com_iflytek_cdstd_hungrycell_tcpserver_buff_ServerData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.iflytek.cdstd.hungrycell.tcpserver.buff.GameServer.ServerData.class, com.iflytek.cdstd.hungrycell.tcpserver.buff.GameServer.ServerData.Builder.class);
      }

      // Construct using com.iflytek.cdstd.hungrycell.tcpserver.buff.GameServer.ServerData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getMessageInfoFieldBuilder();
          getUserInfoFieldBuilder();
          getGoldChangeFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        service_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        uids_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        if (messageInfoBuilder_ == null) {
          messageInfo_ = com.iflytek.cdstd.hungrycell.tcpserver.buff.GameBuff.MessageInfo.getDefaultInstance();
        } else {
          messageInfoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        if (userInfoBuilder_ == null) {
          userInfo_ = com.iflytek.cdstd.hungrycell.tcpserver.buff.GameBuff.UserInfo.getDefaultInstance();
        } else {
          userInfoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        if (goldChangeBuilder_ == null) {
          goldChange_ = com.iflytek.cdstd.hungrycell.tcpserver.buff.GameServer.GoldChange.getDefaultInstance();
        } else {
          goldChangeBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.iflytek.cdstd.hungrycell.tcpserver.buff.GameServer.internal_static_com_iflytek_cdstd_hungrycell_tcpserver_buff_ServerData_descriptor;
      }

      public com.iflytek.cdstd.hungrycell.tcpserver.buff.GameServer.ServerData getDefaultInstanceForType() {
        return com.iflytek.cdstd.hungrycell.tcpserver.buff.GameServer.ServerData.getDefaultInstance();
      }

      public com.iflytek.cdstd.hungrycell.tcpserver.buff.GameServer.ServerData build() {
        com.iflytek.cdstd.hungrycell.tcpserver.buff.GameServer.ServerData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.iflytek.cdstd.hungrycell.tcpserver.buff.GameServer.ServerData buildPartial() {
        com.iflytek.cdstd.hungrycell.tcpserver.buff.GameServer.ServerData result = new com.iflytek.cdstd.hungrycell.tcpserver.buff.GameServer.ServerData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.service_ = service_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          uids_ = java.util.Collections.unmodifiableList(uids_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.uids_ = uids_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000002;
        }
        if (messageInfoBuilder_ == null) {
          result.messageInfo_ = messageInfo_;
        } else {
          result.messageInfo_ = messageInfoBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000004;
        }
        if (userInfoBuilder_ == null) {
          result.userInfo_ = userInfo_;
        } else {
          result.userInfo_ = userInfoBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000008;
        }
        if (goldChangeBuilder_ == null) {
          result.goldChange_ = goldChange_;
        } else {
          result.goldChange_ = goldChangeBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.iflytek.cdstd.hungrycell.tcpserver.buff.GameServer.ServerData) {
          return mergeFrom((com.iflytek.cdstd.hungrycell.tcpserver.buff.GameServer.ServerData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.iflytek.cdstd.hungrycell.tcpserver.buff.GameServer.ServerData other) {
        if (other == com.iflytek.cdstd.hungrycell.tcpserver.buff.GameServer.ServerData.getDefaultInstance()) return this;
        if (other.hasService()) {
          setService(other.getService());
        }
        if (!other.uids_.isEmpty()) {
          if (uids_.isEmpty()) {
            uids_ = other.uids_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureUidsIsMutable();
            uids_.addAll(other.uids_);
          }
          onChanged();
        }
        if (other.hasMessageInfo()) {
          mergeMessageInfo(other.getMessageInfo());
        }
        if (other.hasUserInfo()) {
          mergeUserInfo(other.getUserInfo());
        }
        if (other.hasGoldChange()) {
          mergeGoldChange(other.getGoldChange());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasService()) {
          
          return false;
        }
        if (hasMessageInfo()) {
          if (!getMessageInfo().isInitialized()) {
            
            return false;
          }
        }
        if (hasUserInfo()) {
          if (!getUserInfo().isInitialized()) {
            
            return false;
          }
        }
        if (hasGoldChange()) {
          if (!getGoldChange().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.iflytek.cdstd.hungrycell.tcpserver.buff.GameServer.ServerData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.iflytek.cdstd.hungrycell.tcpserver.buff.GameServer.ServerData) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int service_ ;
      /**
       * <code>required int32 service = 1;</code>
       */
      public boolean hasService() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 service = 1;</code>
       */
      public int getService() {
        return service_;
      }
      /**
       * <code>required int32 service = 1;</code>
       */
      public Builder setService(int value) {
        bitField0_ |= 0x00000001;
        service_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 service = 1;</code>
       */
      public Builder clearService() {
        bitField0_ = (bitField0_ & ~0x00000001);
        service_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Integer> uids_ = java.util.Collections.emptyList();
      private void ensureUidsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          uids_ = new java.util.ArrayList<java.lang.Integer>(uids_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated int32 uids = 2;</code>
       */
      public java.util.List<java.lang.Integer>
          getUidsList() {
        return java.util.Collections.unmodifiableList(uids_);
      }
      /**
       * <code>repeated int32 uids = 2;</code>
       */
      public int getUidsCount() {
        return uids_.size();
      }
      /**
       * <code>repeated int32 uids = 2;</code>
       */
      public int getUids(int index) {
        return uids_.get(index);
      }
      /**
       * <code>repeated int32 uids = 2;</code>
       */
      public Builder setUids(
          int index, int value) {
        ensureUidsIsMutable();
        uids_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 uids = 2;</code>
       */
      public Builder addUids(int value) {
        ensureUidsIsMutable();
        uids_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 uids = 2;</code>
       */
      public Builder addAllUids(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureUidsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, uids_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 uids = 2;</code>
       */
      public Builder clearUids() {
        uids_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }

      private com.iflytek.cdstd.hungrycell.tcpserver.buff.GameBuff.MessageInfo messageInfo_ = com.iflytek.cdstd.hungrycell.tcpserver.buff.GameBuff.MessageInfo.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.iflytek.cdstd.hungrycell.tcpserver.buff.GameBuff.MessageInfo, com.iflytek.cdstd.hungrycell.tcpserver.buff.GameBuff.MessageInfo.Builder, com.iflytek.cdstd.hungrycell.tcpserver.buff.GameBuff.MessageInfoOrBuilder> messageInfoBuilder_;
      /**
       * <code>optional .com.iflytek.cdstd.hungrycell.tcpserver.buff.MessageInfo messageInfo = 3;</code>
       */
      public boolean hasMessageInfo() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .com.iflytek.cdstd.hungrycell.tcpserver.buff.MessageInfo messageInfo = 3;</code>
       */
      public com.iflytek.cdstd.hungrycell.tcpserver.buff.GameBuff.MessageInfo getMessageInfo() {
        if (messageInfoBuilder_ == null) {
          return messageInfo_;
        } else {
          return messageInfoBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.iflytek.cdstd.hungrycell.tcpserver.buff.MessageInfo messageInfo = 3;</code>
       */
      public Builder setMessageInfo(com.iflytek.cdstd.hungrycell.tcpserver.buff.GameBuff.MessageInfo value) {
        if (messageInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          messageInfo_ = value;
          onChanged();
        } else {
          messageInfoBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .com.iflytek.cdstd.hungrycell.tcpserver.buff.MessageInfo messageInfo = 3;</code>
       */
      public Builder setMessageInfo(
          com.iflytek.cdstd.hungrycell.tcpserver.buff.GameBuff.MessageInfo.Builder builderForValue) {
        if (messageInfoBuilder_ == null) {
          messageInfo_ = builderForValue.build();
          onChanged();
        } else {
          messageInfoBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .com.iflytek.cdstd.hungrycell.tcpserver.buff.MessageInfo messageInfo = 3;</code>
       */
      public Builder mergeMessageInfo(com.iflytek.cdstd.hungrycell.tcpserver.buff.GameBuff.MessageInfo value) {
        if (messageInfoBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              messageInfo_ != com.iflytek.cdstd.hungrycell.tcpserver.buff.GameBuff.MessageInfo.getDefaultInstance()) {
            messageInfo_ =
              com.iflytek.cdstd.hungrycell.tcpserver.buff.GameBuff.MessageInfo.newBuilder(messageInfo_).mergeFrom(value).buildPartial();
          } else {
            messageInfo_ = value;
          }
          onChanged();
        } else {
          messageInfoBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .com.iflytek.cdstd.hungrycell.tcpserver.buff.MessageInfo messageInfo = 3;</code>
       */
      public Builder clearMessageInfo() {
        if (messageInfoBuilder_ == null) {
          messageInfo_ = com.iflytek.cdstd.hungrycell.tcpserver.buff.GameBuff.MessageInfo.getDefaultInstance();
          onChanged();
        } else {
          messageInfoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>optional .com.iflytek.cdstd.hungrycell.tcpserver.buff.MessageInfo messageInfo = 3;</code>
       */
      public com.iflytek.cdstd.hungrycell.tcpserver.buff.GameBuff.MessageInfo.Builder getMessageInfoBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getMessageInfoFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.iflytek.cdstd.hungrycell.tcpserver.buff.MessageInfo messageInfo = 3;</code>
       */
      public com.iflytek.cdstd.hungrycell.tcpserver.buff.GameBuff.MessageInfoOrBuilder getMessageInfoOrBuilder() {
        if (messageInfoBuilder_ != null) {
          return messageInfoBuilder_.getMessageOrBuilder();
        } else {
          return messageInfo_;
        }
      }
      /**
       * <code>optional .com.iflytek.cdstd.hungrycell.tcpserver.buff.MessageInfo messageInfo = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.iflytek.cdstd.hungrycell.tcpserver.buff.GameBuff.MessageInfo, com.iflytek.cdstd.hungrycell.tcpserver.buff.GameBuff.MessageInfo.Builder, com.iflytek.cdstd.hungrycell.tcpserver.buff.GameBuff.MessageInfoOrBuilder> 
          getMessageInfoFieldBuilder() {
        if (messageInfoBuilder_ == null) {
          messageInfoBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.iflytek.cdstd.hungrycell.tcpserver.buff.GameBuff.MessageInfo, com.iflytek.cdstd.hungrycell.tcpserver.buff.GameBuff.MessageInfo.Builder, com.iflytek.cdstd.hungrycell.tcpserver.buff.GameBuff.MessageInfoOrBuilder>(
                  getMessageInfo(),
                  getParentForChildren(),
                  isClean());
          messageInfo_ = null;
        }
        return messageInfoBuilder_;
      }

      private com.iflytek.cdstd.hungrycell.tcpserver.buff.GameBuff.UserInfo userInfo_ = com.iflytek.cdstd.hungrycell.tcpserver.buff.GameBuff.UserInfo.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.iflytek.cdstd.hungrycell.tcpserver.buff.GameBuff.UserInfo, com.iflytek.cdstd.hungrycell.tcpserver.buff.GameBuff.UserInfo.Builder, com.iflytek.cdstd.hungrycell.tcpserver.buff.GameBuff.UserInfoOrBuilder> userInfoBuilder_;
      /**
       * <code>optional .com.iflytek.cdstd.hungrycell.tcpserver.buff.UserInfo userInfo = 4;</code>
       *
       * <pre>
       *add by wq 2017-05-26
       * </pre>
       */
      public boolean hasUserInfo() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional .com.iflytek.cdstd.hungrycell.tcpserver.buff.UserInfo userInfo = 4;</code>
       *
       * <pre>
       *add by wq 2017-05-26
       * </pre>
       */
      public com.iflytek.cdstd.hungrycell.tcpserver.buff.GameBuff.UserInfo getUserInfo() {
        if (userInfoBuilder_ == null) {
          return userInfo_;
        } else {
          return userInfoBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.iflytek.cdstd.hungrycell.tcpserver.buff.UserInfo userInfo = 4;</code>
       *
       * <pre>
       *add by wq 2017-05-26
       * </pre>
       */
      public Builder setUserInfo(com.iflytek.cdstd.hungrycell.tcpserver.buff.GameBuff.UserInfo value) {
        if (userInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          userInfo_ = value;
          onChanged();
        } else {
          userInfoBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .com.iflytek.cdstd.hungrycell.tcpserver.buff.UserInfo userInfo = 4;</code>
       *
       * <pre>
       *add by wq 2017-05-26
       * </pre>
       */
      public Builder setUserInfo(
          com.iflytek.cdstd.hungrycell.tcpserver.buff.GameBuff.UserInfo.Builder builderForValue) {
        if (userInfoBuilder_ == null) {
          userInfo_ = builderForValue.build();
          onChanged();
        } else {
          userInfoBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .com.iflytek.cdstd.hungrycell.tcpserver.buff.UserInfo userInfo = 4;</code>
       *
       * <pre>
       *add by wq 2017-05-26
       * </pre>
       */
      public Builder mergeUserInfo(com.iflytek.cdstd.hungrycell.tcpserver.buff.GameBuff.UserInfo value) {
        if (userInfoBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008) &&
              userInfo_ != com.iflytek.cdstd.hungrycell.tcpserver.buff.GameBuff.UserInfo.getDefaultInstance()) {
            userInfo_ =
              com.iflytek.cdstd.hungrycell.tcpserver.buff.GameBuff.UserInfo.newBuilder(userInfo_).mergeFrom(value).buildPartial();
          } else {
            userInfo_ = value;
          }
          onChanged();
        } else {
          userInfoBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .com.iflytek.cdstd.hungrycell.tcpserver.buff.UserInfo userInfo = 4;</code>
       *
       * <pre>
       *add by wq 2017-05-26
       * </pre>
       */
      public Builder clearUserInfo() {
        if (userInfoBuilder_ == null) {
          userInfo_ = com.iflytek.cdstd.hungrycell.tcpserver.buff.GameBuff.UserInfo.getDefaultInstance();
          onChanged();
        } else {
          userInfoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      /**
       * <code>optional .com.iflytek.cdstd.hungrycell.tcpserver.buff.UserInfo userInfo = 4;</code>
       *
       * <pre>
       *add by wq 2017-05-26
       * </pre>
       */
      public com.iflytek.cdstd.hungrycell.tcpserver.buff.GameBuff.UserInfo.Builder getUserInfoBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getUserInfoFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.iflytek.cdstd.hungrycell.tcpserver.buff.UserInfo userInfo = 4;</code>
       *
       * <pre>
       *add by wq 2017-05-26
       * </pre>
       */
      public com.iflytek.cdstd.hungrycell.tcpserver.buff.GameBuff.UserInfoOrBuilder getUserInfoOrBuilder() {
        if (userInfoBuilder_ != null) {
          return userInfoBuilder_.getMessageOrBuilder();
        } else {
          return userInfo_;
        }
      }
      /**
       * <code>optional .com.iflytek.cdstd.hungrycell.tcpserver.buff.UserInfo userInfo = 4;</code>
       *
       * <pre>
       *add by wq 2017-05-26
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.iflytek.cdstd.hungrycell.tcpserver.buff.GameBuff.UserInfo, com.iflytek.cdstd.hungrycell.tcpserver.buff.GameBuff.UserInfo.Builder, com.iflytek.cdstd.hungrycell.tcpserver.buff.GameBuff.UserInfoOrBuilder> 
          getUserInfoFieldBuilder() {
        if (userInfoBuilder_ == null) {
          userInfoBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.iflytek.cdstd.hungrycell.tcpserver.buff.GameBuff.UserInfo, com.iflytek.cdstd.hungrycell.tcpserver.buff.GameBuff.UserInfo.Builder, com.iflytek.cdstd.hungrycell.tcpserver.buff.GameBuff.UserInfoOrBuilder>(
                  getUserInfo(),
                  getParentForChildren(),
                  isClean());
          userInfo_ = null;
        }
        return userInfoBuilder_;
      }

      private com.iflytek.cdstd.hungrycell.tcpserver.buff.GameServer.GoldChange goldChange_ = com.iflytek.cdstd.hungrycell.tcpserver.buff.GameServer.GoldChange.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.iflytek.cdstd.hungrycell.tcpserver.buff.GameServer.GoldChange, com.iflytek.cdstd.hungrycell.tcpserver.buff.GameServer.GoldChange.Builder, com.iflytek.cdstd.hungrycell.tcpserver.buff.GameServer.GoldChangeOrBuilder> goldChangeBuilder_;
      /**
       * <code>optional .com.iflytek.cdstd.hungrycell.tcpserver.buff.GoldChange goldChange = 5;</code>
       *
       * <pre>
       *gs-&gt;tcpserver，由tcpserver执行数据库操作
       * </pre>
       */
      public boolean hasGoldChange() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional .com.iflytek.cdstd.hungrycell.tcpserver.buff.GoldChange goldChange = 5;</code>
       *
       * <pre>
       *gs-&gt;tcpserver，由tcpserver执行数据库操作
       * </pre>
       */
      public com.iflytek.cdstd.hungrycell.tcpserver.buff.GameServer.GoldChange getGoldChange() {
        if (goldChangeBuilder_ == null) {
          return goldChange_;
        } else {
          return goldChangeBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.iflytek.cdstd.hungrycell.tcpserver.buff.GoldChange goldChange = 5;</code>
       *
       * <pre>
       *gs-&gt;tcpserver，由tcpserver执行数据库操作
       * </pre>
       */
      public Builder setGoldChange(com.iflytek.cdstd.hungrycell.tcpserver.buff.GameServer.GoldChange value) {
        if (goldChangeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          goldChange_ = value;
          onChanged();
        } else {
          goldChangeBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .com.iflytek.cdstd.hungrycell.tcpserver.buff.GoldChange goldChange = 5;</code>
       *
       * <pre>
       *gs-&gt;tcpserver，由tcpserver执行数据库操作
       * </pre>
       */
      public Builder setGoldChange(
          com.iflytek.cdstd.hungrycell.tcpserver.buff.GameServer.GoldChange.Builder builderForValue) {
        if (goldChangeBuilder_ == null) {
          goldChange_ = builderForValue.build();
          onChanged();
        } else {
          goldChangeBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .com.iflytek.cdstd.hungrycell.tcpserver.buff.GoldChange goldChange = 5;</code>
       *
       * <pre>
       *gs-&gt;tcpserver，由tcpserver执行数据库操作
       * </pre>
       */
      public Builder mergeGoldChange(com.iflytek.cdstd.hungrycell.tcpserver.buff.GameServer.GoldChange value) {
        if (goldChangeBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010) &&
              goldChange_ != com.iflytek.cdstd.hungrycell.tcpserver.buff.GameServer.GoldChange.getDefaultInstance()) {
            goldChange_ =
              com.iflytek.cdstd.hungrycell.tcpserver.buff.GameServer.GoldChange.newBuilder(goldChange_).mergeFrom(value).buildPartial();
          } else {
            goldChange_ = value;
          }
          onChanged();
        } else {
          goldChangeBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .com.iflytek.cdstd.hungrycell.tcpserver.buff.GoldChange goldChange = 5;</code>
       *
       * <pre>
       *gs-&gt;tcpserver，由tcpserver执行数据库操作
       * </pre>
       */
      public Builder clearGoldChange() {
        if (goldChangeBuilder_ == null) {
          goldChange_ = com.iflytek.cdstd.hungrycell.tcpserver.buff.GameServer.GoldChange.getDefaultInstance();
          onChanged();
        } else {
          goldChangeBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      /**
       * <code>optional .com.iflytek.cdstd.hungrycell.tcpserver.buff.GoldChange goldChange = 5;</code>
       *
       * <pre>
       *gs-&gt;tcpserver，由tcpserver执行数据库操作
       * </pre>
       */
      public com.iflytek.cdstd.hungrycell.tcpserver.buff.GameServer.GoldChange.Builder getGoldChangeBuilder() {
        bitField0_ |= 0x00000010;
        onChanged();
        return getGoldChangeFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.iflytek.cdstd.hungrycell.tcpserver.buff.GoldChange goldChange = 5;</code>
       *
       * <pre>
       *gs-&gt;tcpserver，由tcpserver执行数据库操作
       * </pre>
       */
      public com.iflytek.cdstd.hungrycell.tcpserver.buff.GameServer.GoldChangeOrBuilder getGoldChangeOrBuilder() {
        if (goldChangeBuilder_ != null) {
          return goldChangeBuilder_.getMessageOrBuilder();
        } else {
          return goldChange_;
        }
      }
      /**
       * <code>optional .com.iflytek.cdstd.hungrycell.tcpserver.buff.GoldChange goldChange = 5;</code>
       *
       * <pre>
       *gs-&gt;tcpserver，由tcpserver执行数据库操作
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.iflytek.cdstd.hungrycell.tcpserver.buff.GameServer.GoldChange, com.iflytek.cdstd.hungrycell.tcpserver.buff.GameServer.GoldChange.Builder, com.iflytek.cdstd.hungrycell.tcpserver.buff.GameServer.GoldChangeOrBuilder> 
          getGoldChangeFieldBuilder() {
        if (goldChangeBuilder_ == null) {
          goldChangeBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.iflytek.cdstd.hungrycell.tcpserver.buff.GameServer.GoldChange, com.iflytek.cdstd.hungrycell.tcpserver.buff.GameServer.GoldChange.Builder, com.iflytek.cdstd.hungrycell.tcpserver.buff.GameServer.GoldChangeOrBuilder>(
                  getGoldChange(),
                  getParentForChildren(),
                  isClean());
          goldChange_ = null;
        }
        return goldChangeBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.iflytek.cdstd.hungrycell.tcpserver.buff.ServerData)
    }

    static {
      defaultInstance = new ServerData(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.iflytek.cdstd.hungrycell.tcpserver.buff.ServerData)
  }

  public interface GoldChangeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.iflytek.cdstd.hungrycell.tcpserver.buff.GoldChange)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 uid = 1;</code>
     */
    boolean hasUid();
    /**
     * <code>required int32 uid = 1;</code>
     */
    int getUid();

    /**
     * <code>required int32 gold = 2;</code>
     *
     * <pre>
     *金币变化数
     * </pre>
     */
    boolean hasGold();
    /**
     * <code>required int32 gold = 2;</code>
     *
     * <pre>
     *金币变化数
     * </pre>
     */
    int getGold();

    /**
     * <code>required string type = 3;</code>
     *
     * <pre>
     *金币变化原因，对应gold_record的type
     * </pre>
     */
    boolean hasType();
    /**
     * <code>required string type = 3;</code>
     *
     * <pre>
     *金币变化原因，对应gold_record的type
     * </pre>
     */
    java.lang.String getType();
    /**
     * <code>required string type = 3;</code>
     *
     * <pre>
     *金币变化原因，对应gold_record的type
     * </pre>
     */
    com.google.protobuf.ByteString
        getTypeBytes();
  }
  /**
   * Protobuf type {@code com.iflytek.cdstd.hungrycell.tcpserver.buff.GoldChange}
   */
  public static final class GoldChange extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.iflytek.cdstd.hungrycell.tcpserver.buff.GoldChange)
      GoldChangeOrBuilder {
    // Use GoldChange.newBuilder() to construct.
    private GoldChange(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private GoldChange(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final GoldChange defaultInstance;
    public static GoldChange getDefaultInstance() {
      return defaultInstance;
    }

    public GoldChange getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private GoldChange(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              uid_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              gold_ = input.readInt32();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              type_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.iflytek.cdstd.hungrycell.tcpserver.buff.GameServer.internal_static_com_iflytek_cdstd_hungrycell_tcpserver_buff_GoldChange_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.iflytek.cdstd.hungrycell.tcpserver.buff.GameServer.internal_static_com_iflytek_cdstd_hungrycell_tcpserver_buff_GoldChange_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.iflytek.cdstd.hungrycell.tcpserver.buff.GameServer.GoldChange.class, com.iflytek.cdstd.hungrycell.tcpserver.buff.GameServer.GoldChange.Builder.class);
    }

    public static com.google.protobuf.Parser<GoldChange> PARSER =
        new com.google.protobuf.AbstractParser<GoldChange>() {
      public GoldChange parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GoldChange(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<GoldChange> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int UID_FIELD_NUMBER = 1;
    private int uid_;
    /**
     * <code>required int32 uid = 1;</code>
     */
    public boolean hasUid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 uid = 1;</code>
     */
    public int getUid() {
      return uid_;
    }

    public static final int GOLD_FIELD_NUMBER = 2;
    private int gold_;
    /**
     * <code>required int32 gold = 2;</code>
     *
     * <pre>
     *金币变化数
     * </pre>
     */
    public boolean hasGold() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 gold = 2;</code>
     *
     * <pre>
     *金币变化数
     * </pre>
     */
    public int getGold() {
      return gold_;
    }

    public static final int TYPE_FIELD_NUMBER = 3;
    private java.lang.Object type_;
    /**
     * <code>required string type = 3;</code>
     *
     * <pre>
     *金币变化原因，对应gold_record的type
     * </pre>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string type = 3;</code>
     *
     * <pre>
     *金币变化原因，对应gold_record的type
     * </pre>
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          type_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string type = 3;</code>
     *
     * <pre>
     *金币变化原因，对应gold_record的type
     * </pre>
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      uid_ = 0;
      gold_ = 0;
      type_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasUid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasGold()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, uid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, gold_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getTypeBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, uid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, gold_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getTypeBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.iflytek.cdstd.hungrycell.tcpserver.buff.GameServer.GoldChange parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.iflytek.cdstd.hungrycell.tcpserver.buff.GameServer.GoldChange parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.iflytek.cdstd.hungrycell.tcpserver.buff.GameServer.GoldChange parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.iflytek.cdstd.hungrycell.tcpserver.buff.GameServer.GoldChange parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.iflytek.cdstd.hungrycell.tcpserver.buff.GameServer.GoldChange parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.iflytek.cdstd.hungrycell.tcpserver.buff.GameServer.GoldChange parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.iflytek.cdstd.hungrycell.tcpserver.buff.GameServer.GoldChange parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.iflytek.cdstd.hungrycell.tcpserver.buff.GameServer.GoldChange parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.iflytek.cdstd.hungrycell.tcpserver.buff.GameServer.GoldChange parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.iflytek.cdstd.hungrycell.tcpserver.buff.GameServer.GoldChange parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.iflytek.cdstd.hungrycell.tcpserver.buff.GameServer.GoldChange prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.iflytek.cdstd.hungrycell.tcpserver.buff.GoldChange}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.iflytek.cdstd.hungrycell.tcpserver.buff.GoldChange)
        com.iflytek.cdstd.hungrycell.tcpserver.buff.GameServer.GoldChangeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.iflytek.cdstd.hungrycell.tcpserver.buff.GameServer.internal_static_com_iflytek_cdstd_hungrycell_tcpserver_buff_GoldChange_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.iflytek.cdstd.hungrycell.tcpserver.buff.GameServer.internal_static_com_iflytek_cdstd_hungrycell_tcpserver_buff_GoldChange_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.iflytek.cdstd.hungrycell.tcpserver.buff.GameServer.GoldChange.class, com.iflytek.cdstd.hungrycell.tcpserver.buff.GameServer.GoldChange.Builder.class);
      }

      // Construct using com.iflytek.cdstd.hungrycell.tcpserver.buff.GameServer.GoldChange.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        uid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        gold_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.iflytek.cdstd.hungrycell.tcpserver.buff.GameServer.internal_static_com_iflytek_cdstd_hungrycell_tcpserver_buff_GoldChange_descriptor;
      }

      public com.iflytek.cdstd.hungrycell.tcpserver.buff.GameServer.GoldChange getDefaultInstanceForType() {
        return com.iflytek.cdstd.hungrycell.tcpserver.buff.GameServer.GoldChange.getDefaultInstance();
      }

      public com.iflytek.cdstd.hungrycell.tcpserver.buff.GameServer.GoldChange build() {
        com.iflytek.cdstd.hungrycell.tcpserver.buff.GameServer.GoldChange result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.iflytek.cdstd.hungrycell.tcpserver.buff.GameServer.GoldChange buildPartial() {
        com.iflytek.cdstd.hungrycell.tcpserver.buff.GameServer.GoldChange result = new com.iflytek.cdstd.hungrycell.tcpserver.buff.GameServer.GoldChange(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.uid_ = uid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.gold_ = gold_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.type_ = type_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.iflytek.cdstd.hungrycell.tcpserver.buff.GameServer.GoldChange) {
          return mergeFrom((com.iflytek.cdstd.hungrycell.tcpserver.buff.GameServer.GoldChange)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.iflytek.cdstd.hungrycell.tcpserver.buff.GameServer.GoldChange other) {
        if (other == com.iflytek.cdstd.hungrycell.tcpserver.buff.GameServer.GoldChange.getDefaultInstance()) return this;
        if (other.hasUid()) {
          setUid(other.getUid());
        }
        if (other.hasGold()) {
          setGold(other.getGold());
        }
        if (other.hasType()) {
          bitField0_ |= 0x00000004;
          type_ = other.type_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUid()) {
          
          return false;
        }
        if (!hasGold()) {
          
          return false;
        }
        if (!hasType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.iflytek.cdstd.hungrycell.tcpserver.buff.GameServer.GoldChange parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.iflytek.cdstd.hungrycell.tcpserver.buff.GameServer.GoldChange) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int uid_ ;
      /**
       * <code>required int32 uid = 1;</code>
       */
      public boolean hasUid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 uid = 1;</code>
       */
      public int getUid() {
        return uid_;
      }
      /**
       * <code>required int32 uid = 1;</code>
       */
      public Builder setUid(int value) {
        bitField0_ |= 0x00000001;
        uid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 uid = 1;</code>
       */
      public Builder clearUid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        uid_ = 0;
        onChanged();
        return this;
      }

      private int gold_ ;
      /**
       * <code>required int32 gold = 2;</code>
       *
       * <pre>
       *金币变化数
       * </pre>
       */
      public boolean hasGold() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 gold = 2;</code>
       *
       * <pre>
       *金币变化数
       * </pre>
       */
      public int getGold() {
        return gold_;
      }
      /**
       * <code>required int32 gold = 2;</code>
       *
       * <pre>
       *金币变化数
       * </pre>
       */
      public Builder setGold(int value) {
        bitField0_ |= 0x00000002;
        gold_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 gold = 2;</code>
       *
       * <pre>
       *金币变化数
       * </pre>
       */
      public Builder clearGold() {
        bitField0_ = (bitField0_ & ~0x00000002);
        gold_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object type_ = "";
      /**
       * <code>required string type = 3;</code>
       *
       * <pre>
       *金币变化原因，对应gold_record的type
       * </pre>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string type = 3;</code>
       *
       * <pre>
       *金币变化原因，对应gold_record的type
       * </pre>
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            type_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string type = 3;</code>
       *
       * <pre>
       *金币变化原因，对应gold_record的type
       * </pre>
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string type = 3;</code>
       *
       * <pre>
       *金币变化原因，对应gold_record的type
       * </pre>
       */
      public Builder setType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string type = 3;</code>
       *
       * <pre>
       *金币变化原因，对应gold_record的type
       * </pre>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      /**
       * <code>required string type = 3;</code>
       *
       * <pre>
       *金币变化原因，对应gold_record的type
       * </pre>
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        type_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.iflytek.cdstd.hungrycell.tcpserver.buff.GoldChange)
    }

    static {
      defaultInstance = new GoldChange(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.iflytek.cdstd.hungrycell.tcpserver.buff.GoldChange)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_iflytek_cdstd_hungrycell_tcpserver_buff_ServerData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_iflytek_cdstd_hungrycell_tcpserver_buff_ServerData_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_iflytek_cdstd_hungrycell_tcpserver_buff_GoldChange_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_iflytek_cdstd_hungrycell_tcpserver_buff_GoldChange_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014server.proto\022+com.iflytek.cdstd.hungry" +
      "cell.tcpserver.buff\032\ngame.proto\"\220\002\n\nServ" +
      "erData\022\017\n\007service\030\001 \002(\005\022\014\n\004uids\030\002 \003(\005\022M\n" +
      "\013messageInfo\030\003 \001(\01328.com.iflytek.cdstd.h" +
      "ungrycell.tcpserver.buff.MessageInfo\022G\n\010" +
      "userInfo\030\004 \001(\01325.com.iflytek.cdstd.hungr" +
      "ycell.tcpserver.buff.UserInfo\022K\n\ngoldCha" +
      "nge\030\005 \001(\01327.com.iflytek.cdstd.hungrycell" +
      ".tcpserver.buff.GoldChange\"5\n\nGoldChange" +
      "\022\013\n\003uid\030\001 \002(\005\022\014\n\004gold\030\002 \002(\005\022\014\n\004type\030\003 \002(",
      "\tB9\n+com.iflytek.cdstd.hungrycell.tcpser" +
      "ver.buffB\nGameServer"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.iflytek.cdstd.hungrycell.tcpserver.buff.GameBuff.getDescriptor(),
        }, assigner);
    internal_static_com_iflytek_cdstd_hungrycell_tcpserver_buff_ServerData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_iflytek_cdstd_hungrycell_tcpserver_buff_ServerData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_iflytek_cdstd_hungrycell_tcpserver_buff_ServerData_descriptor,
        new java.lang.String[] { "Service", "Uids", "MessageInfo", "UserInfo", "GoldChange", });
    internal_static_com_iflytek_cdstd_hungrycell_tcpserver_buff_GoldChange_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_iflytek_cdstd_hungrycell_tcpserver_buff_GoldChange_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_iflytek_cdstd_hungrycell_tcpserver_buff_GoldChange_descriptor,
        new java.lang.String[] { "Uid", "Gold", "Type", });
    com.iflytek.cdstd.hungrycell.tcpserver.buff.GameBuff.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
